#!/bin/sh
#
# $Id: reconf,v 1.1.1.1 2003/06/25 17:57:00 hochstenbach Exp $
#
# re autoconf/automake shell script
#

die(){
	echo "$@" ; exit
}

aclocal -I . || die "The command 'aclocal -I .' failed"
autoheader   || die "The command 'autoheader' failed"
automake     || die "The command 'automake' failed"
autoconf     || die "The command 'autoconf' failed"
