#
# $Id: Makefile,v 1.2 2006/12/19 08:33:18 hochstenbach Exp $
#
# Author(s): Patrick Hochstenbach <Patrick.Hochstenbach@UGent.be>
#
BINDIR=../../bin
SBINDIR=../../sbin

install: 
	cp transform.pl $(BINDIR)
	chmod 755 $(BINDIR)/transform.pl

	cp validrepo.pl $(SBINDIR)
	chmod 755 $(SBINDIR)/validrepo.pl

clean:
	@echo Cleaning up
