.\" Written by Patrick Hochstenbach <hochsten@lanl.gov>
.TH dbexport 1 "5 December 2002" "dbexport" "dbexport manual"
.SH NAME
dbexport \-  export the contents of a gdbm database
.SH SYNOPSIS
.B dbexport file
.SH DESCRIPTION
This commands exports the content of a gdbm database as a tab delimited list.
.SH "SEE ALSO"
.BR gdbm (3),
.SH BUGS
No bugs known at this date. Please mail me <hochsten@lanl.gov> if you find some.
